namespace DreamPoeBot.Loki.Game.GameData;

public enum InventoryType
{
	Main = 0,
	Chest = 1,
	LeftHand = 2,
	RightHand = 3,
	Head = 4,
	Neck = 5,
	Rings = 6,
	Gloves = 7,
	Boots = 8,
	Belt = 9,
	Flasks = 10,
	Cursor = 11,
	MapDevice = 12,
	PassiveTree = 13,
	Stash = 15,
	Leaguestone = 16,
	CurrencyTab = 18,
	EssenceTab = 21,
	FragmentTab = 22,
	MapTab = 23,
	DelveTab = 27,
	WatchstoneContainer = 28,
	EspeditionLocker = 29,
	BlightTab = 31,
	MetamorphTab = 33,
	HeistLooker = 36,
	BloodCrucible = 45,
	Sentinel = 48,
	SentinelLocker = 49,
	NormalTab = 50,
	ExpeditionLogBook = 55
}
