namespace DreamPoeBot.Loki.Game.GameData;

public enum InventorySlot
{
	Main = 0,
	Chest = 1,
	LeftHand = 2,
	RightHand = 3,
	Head = 4,
	Neck = 5,
	LeftRing = 6,
	RightRing = 7,
	Gloves = 8,
	Boots = 9,
	Belt = 10,
	Flasks = 11,
	Cursor = 12,
	Slot4MapDevice = 13,
	OffLeftHand = 14,
	OffRightHand = 15,
	ArmourersWorkbench = 16,
	SharpeningWheel = 17,
	BowmakersTools = 18,
	ArtisansBench = 19,
	Headstones = 20,
	BlessingFont = 21,
	PassiveTreeJewels = 23,
	UnknowMapDevice = 25,
	Stash = 26,
	Divination = 27,
	DarkShrine = 28,
	Talisman = 29,
	Leaguestone = 30,
	BeastCrafting = 31,
	TableOfSacrifice = 32,
	LapidaryLensUi = 33,
	AnointOils = 36,
	AnointMain = 37,
	CitadelsWatchstone = 39,
	AtlasInventory = 40,
	ExpeditionMap = 41,
	HeistLooker = 56,
	Sentinel = 72,
	SentinelLocker = 73
}
